defmodule Boxart.Charset do
  @moduledoc """
  Character sets for Unicode and ASCII box-drawing rendering.

  Each `Charset` struct holds all glyphs needed to draw nodes, edges,
  corners, arrows, and subgraph borders.
  """

  @type t :: %__MODULE__{
          top_left: String.t(),
          top_right: String.t(),
          bottom_left: String.t(),
          bottom_right: String.t(),
          horizontal: String.t(),
          vertical: String.t(),
          round_top_left: String.t(),
          round_top_right: String.t(),
          round_bottom_left: String.t(),
          round_bottom_right: String.t(),
          arrow_right: String.t(),
          arrow_left: String.t(),
          arrow_down: String.t(),
          arrow_up: String.t(),
          line_horizontal: String.t(),
          line_vertical: String.t(),
          line_dotted_h: String.t(),
          line_dotted_v: String.t(),
          line_thick_h: String.t(),
          line_thick_v: String.t(),
          corner_top_left: String.t(),
          corner_top_right: String.t(),
          corner_bottom_left: String.t(),
          corner_bottom_right: String.t(),
          tee_right: String.t(),
          tee_left: String.t(),
          tee_down: String.t(),
          tee_up: String.t(),
          cross: String.t(),
          diamond_top: String.t(),
          diamond_bottom: String.t(),
          diamond_left: String.t(),
          diamond_right: String.t(),
          circle_endpoint: String.t(),
          cross_endpoint: String.t(),
          sg_top_left: String.t(),
          sg_top_right: String.t(),
          sg_bottom_left: String.t(),
          sg_bottom_right: String.t(),
          sg_horizontal: String.t(),
          sg_vertical: String.t()
        }

  defstruct [
    :top_left,
    :top_right,
    :bottom_left,
    :bottom_right,
    :horizontal,
    :vertical,
    :round_top_left,
    :round_top_right,
    :round_bottom_left,
    :round_bottom_right,
    :arrow_right,
    :arrow_left,
    :arrow_down,
    :arrow_up,
    :line_horizontal,
    :line_vertical,
    :line_dotted_h,
    :line_dotted_v,
    :line_thick_h,
    :line_thick_v,
    :corner_top_left,
    :corner_top_right,
    :corner_bottom_left,
    :corner_bottom_right,
    :tee_right,
    :tee_left,
    :tee_down,
    :tee_up,
    :cross,
    :diamond_top,
    :diamond_bottom,
    :diamond_left,
    :diamond_right,
    :circle_endpoint,
    :cross_endpoint,
    :sg_top_left,
    :sg_top_right,
    :sg_bottom_left,
    :sg_bottom_right,
    :sg_horizontal,
    :sg_vertical
  ]

  @doc "Returns a charset using Unicode box-drawing characters."
  @spec unicode() :: t()
  def unicode do
    %__MODULE__{
      top_left: "┌",
      top_right: "┐",
      bottom_left: "└",
      bottom_right: "┘",
      horizontal: "─",
      vertical: "│",
      round_top_left: "╭",
      round_top_right: "╮",
      round_bottom_left: "╰",
      round_bottom_right: "╯",
      arrow_right: "►",
      arrow_left: "◄",
      arrow_down: "▼",
      arrow_up: "▲",
      line_horizontal: "─",
      line_vertical: "│",
      line_dotted_h: "┄",
      line_dotted_v: "┆",
      line_thick_h: "━",
      line_thick_v: "┃",
      corner_top_left: "┌",
      corner_top_right: "┐",
      corner_bottom_left: "└",
      corner_bottom_right: "┘",
      tee_right: "├",
      tee_left: "┤",
      tee_down: "┬",
      tee_up: "┴",
      cross: "┼",
      diamond_top: "◇",
      diamond_bottom: "◇",
      diamond_left: "◇",
      diamond_right: "◇",
      circle_endpoint: "○",
      cross_endpoint: "×",
      sg_top_left: "┌",
      sg_top_right: "┐",
      sg_bottom_left: "└",
      sg_bottom_right: "┘",
      sg_horizontal: "─",
      sg_vertical: "│"
    }
  end

  @doc "Returns a charset using plain ASCII characters."
  @spec ascii() :: t()
  def ascii do
    %__MODULE__{
      top_left: "+",
      top_right: "+",
      bottom_left: "+",
      bottom_right: "+",
      horizontal: "-",
      vertical: "|",
      round_top_left: "+",
      round_top_right: "+",
      round_bottom_left: "+",
      round_bottom_right: "+",
      arrow_right: ">",
      arrow_left: "<",
      arrow_down: "v",
      arrow_up: "^",
      line_horizontal: "-",
      line_vertical: "|",
      line_dotted_h: ".",
      line_dotted_v: ":",
      line_thick_h: "=",
      line_thick_v: "H",
      corner_top_left: "+",
      corner_top_right: "+",
      corner_bottom_left: "+",
      corner_bottom_right: "+",
      tee_right: "+",
      tee_left: "+",
      tee_down: "+",
      tee_up: "+",
      cross: "+",
      diamond_top: "/",
      diamond_bottom: "\\",
      diamond_left: "/",
      diamond_right: "\\",
      circle_endpoint: "o",
      cross_endpoint: "x",
      sg_top_left: "+",
      sg_top_right: "+",
      sg_bottom_left: "+",
      sg_bottom_right: "+",
      sg_horizontal: "-",
      sg_vertical: "|"
    }
  end
end
